# Generated by Django 4.0.8 on 2022-10-27 20:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiStop',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('address_fr', models.TextField(blank=True, null=True, verbose_name='address')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates if this taxi stop should be treated as active.', verbose_name='active')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='localization.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'taxi stop',
                'verbose_name_plural': 'taxi stops',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaxiRoute',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.PositiveSmallIntegerField(choices=[(1, 'Car'), (2, 'Motorcycle')], default=1, verbose_name='mode')),
                ('std_price', models.PositiveSmallIntegerField(default=100, verbose_name='standard price')),
                ('night_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='night price')),
                ('jam_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='traffic jam price')),
                ('hurry_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='emergency price')),
                ('rain_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rain price')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('notes_fr', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('notes_en', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this route should be treated as active.', verbose_name='active')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to_here', to='taxi.taxistop', verbose_name='destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from_here', to='taxi.taxistop', verbose_name='origin')),
            ],
            options={
                'verbose_name': 'taxi route',
                'verbose_name_plural': 'taxi routes',
                'ordering': ('std_price',),
            },
        ),
        migrations.AddConstraint(
            model_name='taxistop',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'city'), name='unique_name_and_city_for_taxi_stop'),
        ),
        migrations.AddConstraint(
            model_name='taxiroute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('origin', 'destination', 'mode'), name='unique_origin_destination_and_mode_for_taxi_route'),
        ),
    ]
