name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore: [ "docs/**" ]
  pull_request:
    branches: [ "master", "develop" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      postgres:
        image: postgis/postgis:14-3.3
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    env:
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            apps/api/requirements/base.txt
            apps/api/requirements/local.txt

      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: develop

      - run: yarn install
      - run: npx nx affected --target=install --parallel=3

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            npx nx affected --target=lint --parallel=3
            npx nx affected --target=test --parallel=3 --code-coverage
            npx nx affected --target=build --parallel=3

      - name: Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/apps/web/lcov.info,./apps/api/coverage.xml
          fail_ci_if_error: false
