name: "CI Webapp"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

on:
  workflow_call:
    paths:
      - "apps/web/**"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: test
    env:
      NX_API_ROOT: ${{ secrets.API_ROOT }}
      NX_API_VERSION: ${{ secrets.API_VERSION }}
      NX_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn install && npx nx build web --configuration production --skip-nx-cache
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ secrets.GCP_PROJECT_ID }}
